export: Command not found.
export: Command not found.
export: Command not found.
export: Command not found.
Badly placed ()'s.
 
Running threaded PSI4 on node17 
/home/mdavis/anaconda3/envs/p4env/bin/psi4
 
Working and scratch directories
/home/mdavis/f12eom_optimizer/tests/slurm
/scratch/mdavis/PSI4_2022-08-17_15:50:32.925600688
 
use -n:  to specify number of threads
use -i:  to specify input  file     (default = input.dat)
use -o:  to specify output file     (default = file.out )
 
-h or --help for more options
 
Running...
Traceback (most recent call last):
  File "/home/mdavis/f12eom_optimizer/f12eom_optimizer/f12eom_optimizer.py", line 236, in <module>
    main()
  File "/home/mdavis/f12eom_optimizer/f12eom_optimizer/f12eom_optimizer.py", line 169, in main
    h2o = psi4.geometry(f"""
  File "/home/mdavis/anaconda3/envs/p4env/lib/python3.10/site-packages/psi4/driver/molutil.py", line 259, in geometry
    molrec = qcel.molparse.from_string(
  File "/home/mdavis/anaconda3/envs/p4env/lib/python3.10/site-packages/qcelemental/molparse/from_string.py", line 276, in from_string
    molrec = from_input_arrays(
  File "/home/mdavis/anaconda3/envs/p4env/lib/python3.10/site-packages/qcelemental/molparse/from_arrays.py", line 97, in from_input_arrays
    processed = from_arrays(
  File "/home/mdavis/anaconda3/envs/p4env/lib/python3.10/site-packages/qcelemental/molparse/from_arrays.py", line 371, in from_arrays
    processed = validate_and_fill_fragments(
  File "/home/mdavis/anaconda3/envs/p4env/lib/python3.10/site-packages/qcelemental/molparse/from_arrays.py", line 762, in validate_and_fill_fragments
    raise ValidationError(
qcelemental.exceptions.ValidationError: fragment_multiplicities not among None or positive integer: [0]
...Done
 
